jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      GHC 8.6:
        ARGS: "--stack-yaml stack-ghc-86.yaml"
      GHC 8.8:
        ARGS: "--stack-yaml stack-ghc-88.yaml"
      GHC 9.2.2:
        ARGS: "--stack-yaml stack-ghc-922.yaml"
      persistent 2.11:
        ARGS: "--stack-yaml stack-persistent-211.yaml"
      persistent 2.13:
        ARGS: "--stack-yaml stack-persistent-213.yaml"
      Cabal 3.4.0.0:
        ARGS: "--stack-yaml stack-cabal-3.4.yaml"
      aeson 2:
        ARGS: "--stack-yaml stack-aeson2.yaml"
    maxParallel: 6
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
