jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      GHC 8.6:
        ARGS: "--stack-yaml stack-ghc-86.yaml"
      # Buggy :(
      #GHC 8.8:
      #  ARGS: "--stack-yaml stack.yaml"
      GHC 9.2.2:
        ARGS: "--stack-yaml stack-ghc-922.yaml"
    maxParallel: 3
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack $ARGS test --bench --no-run-benchmarks
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
