name: Tests

on:
  pull_request:
  push:
    branches:
    - master

# As of 28 August 2022, ubuntu-latest, windows-latest and macos-latest come with
# Stack 2.7.5.

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        stack-yaml:
        - stack-ghc-8.6.5.yaml
        - stack-ghc-8.8.4.yaml
        - stack-ghc-9.2.4.yaml
        - stack-ghc-9.4.2.yaml
        - stack-persistent-2.11.yaml
        - stack-cabal-3.4.yaml
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Cache dependencies on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}
    - name: Cache dependencies on Windows
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v3
      with:
        path: |
           ~\AppData\Roaming\stack
           ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}
    - name: Build and run tests
      shell: bash
      run: |
        set -ex
        stack test --stack-yaml ${{ matrix.stack-yaml }} --bench --no-run-benchmarks --haddock --no-haddock-deps
